spring.application.name=SmartChef

# --- Conexion a la base de datos -----------------------------
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.hikari.schema=${DB_SCHEMA}

# --- JPA / Hibernate -----------------------------------------
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# --- Servidor ------------------------------------------------
server.port=8080
